Repository LoopKit/loopdocs, pull requests merged in 2023-07, with the labels that each got.

#664 📝 Update README + 🌐 Add sections including how to improve "Automatic Translation"
  README.md
Labels: typo, translation

#672 🚚 Update LoopFollow Github URL
  docs/gh-actions/gh-other-apps.md
Labels: doc

#657 Additions to Nightscout Remote Commands Documentation
  docs/nightscout/remote-overrides.md
Labels: enhancement, typo, translation

#673 Updates to Retrospective Correction description
  docs/operation/algorithm/img/bgrc_graphic.png
  docs/operation/algorithm/img/combined_effects.png
  docs/operation/algorithm/prediction.md
Labels: doc

#677 ✏️ Fix a Typo in `gh-other-apps` page
  docs/gh-actions/gh-other-apps.md
Labels: typo

#678 📝 Update automatic translation and add a section on how to deploy a branch for preview with GitHub Pages
  README.md
  img/gh_pages_config.png
Labels: enhancement, typo, translation

#679 ✏️ Fix typos in README and add line breaks where missing
  README.md
Labels: typo
