Repository LoopKit/loopdocs, pull requests merged in 2024-05, with the labels that each got.

#813 Change explanation of insulin activity
  docs/operation/algorithm/prediction.md
Labels: typo

#825 ⬆️ Upgrade Dependencies
  mkdocs.yml
  requirements.txt
Labels: dependencies, config

#827 ➖ Remove mkdocs-material-extensions now deprecated
  requirements.txt
Labels: dependencies

#830 ✏️ Fix typos
  docs/build/pump.md
  docs/gh-actions/gh-errors.md
Labels: typo

#829 ✏️ Fix broken anchors in links
  docs/build/build-app.md
  docs/build/build-errors.md
  docs/build/overview.md
  docs/build/updating.md
  docs/faqs/loop-faqs.md
  docs/faqs/new-phone.md
  docs/faqs/rileylink-faqs.md
  docs/gh-actions/automatic.md
  docs/gh-actions/edit-browser.md
  docs/gh-actions/gh-deploy.md
  docs/gh-actions/gh-first-time.md
  docs/intro/requirements.md
  docs/loop-3/add-cgm.md
  docs/loop-3/features.md
  docs/loop-3/medtronic.md
  docs/operation/algorithm/prediction.md
  docs/operation/loop-settings/cgm.md
  docs/operation/loop-settings/displays.md
  docs/operation/loop-settings/pump-commands.md
  docs/operation/loop-settings/rileylink.md
  docs/troubleshooting/red-loop.md
  docs/version/loopworkspace.md
  docs/version/simulator.md
Labels: typo
